python .\realtime_ksl_keypoint_infer.py `
  --model_path ".\models\ksl_keypoint_tcn_best.pt" `
  --label_map_path ".\models\label_map.json" `
  --camera 0 `
  --window_frames 120 `
  --multi_windows 72,96,120 `
  --min_window_frames 60 `
  --predict_every 5 `
  --topk 5 `
  --conf_threshold 0.40 `
  --majority_ratio 0.50 `
  --smooth_history 18 `
  --min_commit_history 8 `
  --cooldown_sec 1.3 `
  --repeat_cooldown_sec 2.8 `
  --max_missing_ratio 0.60 `
  --hold_missing_hands 10